version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  experiment-enqueuer:
    build: .
    restart: always
    entrypoint: ["python", "-u" ,"-m", "stax.microservices.experiment_enqueuer"]
    depends_on:
      - redis
      - core-worker
    ports:
      - "5000:5000"
    environment:
      - STAX_BACKEND_URI=${STAX_BACKEND_URI}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - REDIS_HOST=redis

  core-worker:
    build: .
    entrypoint: ["rq", "worker", "-u", "redis://redis:6379"]
    depends_on:
      - redis
    environment:
      - STAX_BACKEND_URI=${STAX_BACKEND_URI}
      - REDIS_HOST=redis

  completion-watcher:
    build: .
    entrypoint: ["python", "-u" ,"-m", "stax.microservices.completion_watcher"]
    depends_on:
      - redis
    environment:
      - STAX_BACKEND_URI=${STAX_BACKEND_URI}
      - REDIS_HOST=redis
      - MONGO_DB_URI=${MONGO_DB_URI}
